# Setup
title:        Zaihan's blog
description: Notes on Infrastructure and Software Development
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Muhammad Nuzaihan Kamal Luddin
  url:        https://unrealasia.net

#Others
markdown: kramdown
google_analytics: UA-39699714-11 
